#!/bin/bash
#PBS -N merge_G1
#PBS -l nodes=1:ppn=1
#PBS -o L4.out
#PBS -e L4.err
#PBS -l walltime=2400:0:0
#PBS -q batch
echo "Start at"
date
cd $PBS_O_WORKDIR
for ID in s79 s66 s1 s3 s4 s15
do
/public/home/cotton/software/tabix-0.2.6/bgzip ${ID}.concordance.filter1.snp.vcf
/public/home/cotton/software/tabix-0.2.6/tabix -p vcf ${ID}.concordance.filter1.snp.vcf.gz
/public/home/cotton/software/tabix-0.2.6/bgzip ${ID}.concordance.filter1.vcf
/public/home/cotton/software/tabix-0.2.6/tabix -p vcf ${ID}.concordance.filter1.vcf.gz
done
#merge snp
nohup /public/home/jyli/software/vcftools-vcftools-1d27c24/src/perl/vcf-merge s79.concordance.filter1.snp.vcf.gz s66.concordance.filter1.snp.vcf.gz s1.concordance.filter1.snp.vcf.gz > /public/home/jyli/CRISPR/2017-09-05/s1_s3_s4_s14_ForGene1/SNP/s1.merge.snp.vcf &
nohup /public/home/jyli/software/vcftools-vcftools-1d27c24/src/perl/vcf-merge s79.concordance.filter1.snp.vcf.gz s66.concordance.filter1.snp.vcf.gz s3.concordance.filter1.snp.vcf.gz > /public/home/jyli/CRISPR/2017-09-05/s1_s3_s4_s14_ForGene1/SNP/s3.merge.snp.vcf &
nohup /public/home/jyli/software/vcftools-vcftools-1d27c24/src/perl/vcf-merge s79.concordance.filter1.snp.vcf.gz s66.concordance.filter1.snp.vcf.gz s4.concordance.filter1.snp.vcf.gz > /public/home/jyli/CRISPR/2017-09-05/s1_s3_s4_s14_ForGene1/SNP/s4.merge.snp.vcf &
nohup /public/home/jyli/software/vcftools-vcftools-1d27c24/src/perl/vcf-merge s79.concordance.filter1.snp.vcf.gz s66.concordance.filter1.snp.vcf.gz s15.concordance.filter1.snp.vcf.gz > /public/home/jyli/CRISPR/2017-09-05/s1_s3_s4_s14_ForGene1/SNP/s15.merge.snp.vcf &
nohup /public/home/jyli/software/vcftools-vcftools-1d27c24/src/perl/vcf-merge s79.concordance.filter1.snp.vcf.gz s66.concordance.filter1.snp.vcf.gz s1.concordance.filter1.snp.vcf.gz s3.concordance.filter1.snp.vcf.gz s4.concordance.filter1.snp.vcf.gz s15.concordance.filter1.snp.vcf.gz >/public/home/jyli/CRISPR/2017-09-05/s1_s3_s4_s14_ForGene1/SNP/s1_s3_s4_s15.merge.snp.vcf &
#merge Indel
nohup /public/home/jyli/software/vcftools-vcftools-1d27c24/src/perl/vcf-merge s79.comm.indel.vcf.gz s66.comm.indel.vcf.gz s1.comm.indel.vcf.gz > /public/home/jyli/CRISPR/2017-09-05/s1_s3_s4_s14_ForGene1/Indel/s1.merge.indel.vcf &
nohup /public/home/jyli/software/vcftools-vcftools-1d27c24/src/perl/vcf-merge s79.comm.indel.vcf.gz s66.comm.indel.vcf.gz s3.comm.indel.vcf.gz > /public/home/jyli/CRISPR/2017-09-05/s1_s3_s4_s14_ForGene1/Indel/s3.merge.indel.vcf &
nohup /public/home/jyli/software/vcftools-vcftools-1d27c24/src/perl/vcf-merge s79.comm.indel.vcf.gz s66.comm.indel.vcf.gz s4.comm.indel.vcf.gz > /public/home/jyli/CRISPR/2017-09-05/s1_s3_s4_s14_ForGene1/Indel/s4.merge.indel.vcf &
nohup /public/home/jyli/software/vcftools-vcftools-1d27c24/src/perl/vcf-merge s79.comm.indel.vcf.gz s66.comm.indel.vcf.gz s15.comm.indel.vcf.gz > /public/home/jyli/CRISPR/2017-09-05/s1_s3_s4_s14_ForGene1/Indel/s15.merge.indel.vcf &
nohup /public/home/jyli/software/vcftools-vcftools-1d27c24/src/perl/vcf-merge s79.comm.indel.vcf.gz s66.comm.indel.vcf.gz s1.comm.indel.vcf.gz s3.comm.indel.vcf.gz s4.comm.indel.vcf.gz s15.comm.indel.vcf.gz >/public/home/jyli/CRISPR/2017-09-05/s1_s3_s4_s14_ForGene1/Indel/s1_s3_s4_s15.merge.indel.vcf
exit 0
gunzip *.gz 
rm -f *.snp.vcf.gz.tbi
echo "End at:"
date
