#!/bin/bash
#PBS -N TrimData
#PBS -l nodes=1:ppn=5
#PBS -o Trim.out
#PBS -e Trim.err
#PBS -q batch
#PBS -l walltime=100:0:0
cd /public/home/jyli/RawData/Off_Target_Projet/SRA
for ID in AP2_s1 AP2_s3 AP2_s4 AP2_s15 AP2_s20 AP2_s23 MYB44_s62 MYB44_s75 MYB44_s76 MYB44_s77 Ne_s65 Ne_s66 Ne_s67 WT_s195 WT_s199 WT_s79
do
java -jar /public/home/cotton/software/Trimmomatic/trimmomatic-0.32.jar PE -threads 5 -phred33 -trimlog ${ID}_trim.log ${ID}_R1_001.fastq.gz ${ID}_R2_001.fastq.gz  ./${ID}_1.clean.fastq.gz ./${ID}_1.unpaired.fastq.gz ./${ID}_2.clean.fastq.gz ./${ID}_2.unpaired.fastq.gz ILLUMINACLIP:/public/home/cotton/software/Trimmomatic/adapters/TruSeq3-PE.fa:2:30:10 LEADING:5 TRAILING:5 SLIDINGWINDOW:4:20 MINLEN:75
done
